### PR TITLE
Add support for Linux systems

### PR DESCRIPTION
**Pull request by danielerat**
### What's This PR About?
This pull request aims to enhance RunJS by adding support for Linux systems. The changes primarily focus on modifying two key files: index.js and readme.md. These alterations are essential to ensure seamless functionality on Linux, specifically tested and validated on Ubuntu.

Changes Made
1. index.js
Implemented Linux-specific compatibility improvements.
Addressed potential issues related to Linux file paths and system calls.
Ensured the application behaves consistently across different operating systems.
2. readme.md
Updated the documentation to reflect the newly added Linux support.
Provided clear instructions for Linux users on how to set up and run RunJS.
Included any additional information or requirements specific to Linux.

### CODE REVIEW

**Comment by Pab450** [comment]
Thank you for your pull request, please format the code so that I can merge.

**Comment by varaskkar** [comment]
I just tested it and the process works fine in Manjaro (Arch Linux), but when opening RunJS it still asks for the license. Maybe it's because of the cracker itself, I don't know. I use RunJS 2.9.0

**Comment by varaskkar** [comment]
> > I just tested it and the process works fine in Manjaro (Arch Linux), but when opening RunJS it still asks for the license. Maybe it's because of the cracker itself, I don't know. I use RunJS 2.9.0
> 
> Thx ! Try to enter any license key ? this problem is due to issue #2 maybe.

It works!!! just had to insert any character in the license field and voilá 🎉

**Comment by Luca4316** [comment]
> > > I just tested it and the process works fine in Manjaro (Arch Linux), but when opening RunJS it still asks for the license. Maybe it's because of the cracker itself, I don't know. I use RunJS 2.9.0
> > 
> > 
> > Thx ! Try to enter any license key ? this problem is due to issue #2 maybe.
> 
> It works!!! just had to insert any character in the license field and voilá 🎉
> 
> **Edit**: whenever I close RunJS, it asks again the license but if I insert any character it works once again (it's like when I close RunJS, doesn't save the license for the next time)

In my opinion i don't think you can make this with no problem. The problem is clear there are only 2 pieces of the product to develop this year. So we can make it together i think so ? Or we draw a new paperboard ?

**Comment by Pab450** [comment]
> > > I just tested it and the process works fine in Manjaro (Arch Linux), but when opening RunJS it still asks for the license. Maybe it's because of the cracker itself, I don't know. I use RunJS 2.9.0
> > 
> > 
> > Thx ! Try to enter any license key ? this problem is due to issue #2 maybe.
> 
> It works!!! just had to insert any character in the license field and voilá 🎉
> 
> **Edit**: whenever I close RunJS, it asks again the license but if I insert any character it works once again (it's like when I close RunJS, doesn't save the license for the next time)

Yes, it's a known bug, I'll try to fix it when I have more free time.

**Comment by danielerat** [comment]
All good now regarding the code formatting.

**Review by Pab450 — APPROVED** [review]

**Pull request merged**
